language: c
compiler: 
    - gcc
    - clang
env:
    - CFLAGS="-Wall -pedantic -g -DUNIX_HOST"
    - CFLAGS="-m32 -Wall -pedantic -g -DUNIX_HOST"
install: 
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-multilib lib32readline6-dev
script: make && make test
